"""initial

Revision ID: 37a7f88fb0dc
Revises: 
Create Date: 2026-03-14 02:48:15.596921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a7f88fb0dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downtime_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gauge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gauge_no', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('gauge_type', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('serial_no', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('calibration_interval', sa.Integer(), nullable=True),
    sa.Column('last_calibration', sa.Date(), nullable=True),
    sa.Column('next_calibration', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gauge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gauge_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gauge_gauge_no'), ['gauge_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_gauge_status'), ['status'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tool_error_title_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('tool_masterdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_no', sa.String(length=100), nullable=False),
    sa.Column('article_no', sa.String(length=100), nullable=True),
    sa.Column('article_name', sa.String(length=255), nullable=True),
    sa.Column('shot_weight_g', sa.Float(), nullable=True),
    sa.Column('cycle_time_s', sa.Float(), nullable=True),
    sa.Column('cavities', sa.Integer(), nullable=True),
    sa.Column('pack_unit', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('tool_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_masterdata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_masterdata_article_name'), ['article_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_masterdata_article_no'), ['article_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_masterdata_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_masterdata_tool_no'), ['tool_no'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gauge_calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gauge_id', sa.Integer(), nullable=True),
    sa.Column('calibration_date', sa.Date(), nullable=True),
    sa.Column('next_calibration', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('certificate_no', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gauge_id'], ['gauge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gauge_calibration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gauge_calibration_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gauge_calibration_gauge_id'), ['gauge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gauge_calibration_result'), ['result'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('tool_no', sa.String(length=50), nullable=True),
    sa.Column('is_project', sa.Boolean(), nullable=True),
    sa.Column('article', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('project_leader_id', sa.Integer(), nullable=True),
    sa.Column('article_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('target_qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_leader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_no'), ['order_no'], unique=True)

    op.create_table('qm_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_masterdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_error_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('error_no', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_masterdata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('error_no')
    )
    op.create_table('qm_plan_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('revision', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('released_by_id', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_dirty', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['qm_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantity_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('good_qty', sa.Integer(), nullable=True),
    sa.Column('scrap_qty', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('process', sa.String(length=20), nullable=True),
    sa.Column('tool_no', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('prev_order_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('downtime_reason_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['downtime_reason_id'], ['downtime_reasons.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_error_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['tool_error_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qm_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['qm_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['qm_plan_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qm_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('drawing_path', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['plan_version_id'], ['qm_plan_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qm_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qm_sections_plan_version_id'), ['plan_version_id'], unique=False)

    op.create_table('qm_characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('target_value', sa.String(length=50), nullable=True),
    sa.Column('tolerance_minus', sa.String(length=50), nullable=True),
    sa.Column('tolerance_plus', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['qm_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qm_characteristics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qm_characteristics_section_id'), ['section_id'], unique=False)

    op.create_table('qm_dimension_snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['qm_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qm_gauge_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('gauge_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gauge_id'], ['gauge.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['qm_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qm_gauge_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qm_gauge_checks_section_id'), ['section_id'], unique=False)

    op.create_table('qm_section_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['qm_sections.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qm_section_images')
    with op.batch_alter_table('qm_gauge_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qm_gauge_checks_section_id'))

    op.drop_table('qm_gauge_checks')
    op.drop_table('qm_dimension_snippets')
    with op.batch_alter_table('qm_characteristics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qm_characteristics_section_id'))

    op.drop_table('qm_characteristics')
    with op.batch_alter_table('qm_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qm_sections_plan_version_id'))

    op.drop_table('qm_sections')
    op.drop_table('qm_change_logs')
    op.drop_table('tool_error_images')
    op.drop_table('time_bookings')
    op.drop_table('quantity_reports')
    op.drop_table('qm_plan_versions')
    op.drop_table('tool_error_reports')
    op.drop_table('qm_plans')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_no'))

    op.drop_table('orders')
    with op.batch_alter_table('gauge_calibration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gauge_calibration_result'))
        batch_op.drop_index(batch_op.f('ix_gauge_calibration_gauge_id'))
        batch_op.drop_index(batch_op.f('ix_gauge_calibration_created_at'))

    op.drop_table('gauge_calibration')
    op.drop_table('users')
    with op.batch_alter_table('tool_masterdata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_masterdata_tool_no'))
        batch_op.drop_index(batch_op.f('ix_tool_masterdata_location'))
        batch_op.drop_index(batch_op.f('ix_tool_masterdata_article_no'))
        batch_op.drop_index(batch_op.f('ix_tool_masterdata_article_name'))

    op.drop_table('tool_masterdata')
    op.drop_table('tool_error_title_presets')
    op.drop_table('machines')
    with op.batch_alter_table('gauge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gauge_status'))
        batch_op.drop_index(batch_op.f('ix_gauge_gauge_no'))
        batch_op.drop_index(batch_op.f('ix_gauge_created_at'))

    op.drop_table('gauge')
    op.drop_table('downtime_reasons')
    # ### end Alembic commands ###
