"""add entity_name

Revision ID: a53f454956de
Revises: 40efbb14cf19
Create Date: 2026-03-26 22:03:41.440469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53f454956de'
down_revision = '40efbb14cf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_name', sa.String(length=200), nullable=True))

    with op.batch_alter_table('qm_plans', schema=None) as batch_op:
        batch_op.alter_column('tool_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('uq_qm_plan_article_tool', ['article_id', 'tool_id'])

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.alter_column('centering_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tool_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_tools_location'))
        batch_op.drop_index(batch_op.f('ix_tools_tool_no'))
        batch_op.create_unique_constraint(None, ['tool_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_tools_tool_no'), ['tool_no'], unique=1)
        batch_op.create_index(batch_op.f('ix_tools_location'), ['location'], unique=False)
        batch_op.alter_column('tool_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('centering_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('qm_plans', schema=None) as batch_op:
        batch_op.drop_constraint('uq_qm_plan_article_tool', type_='unique')
        batch_op.alter_column('tool_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.drop_column('entity_name')

    op.create_table('_alembic_tmp_qm_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tool_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_qm_plans_article_id')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'tool_id', name=op.f('uq_qm_plan_article_tool'))
    )
    # ### end Alembic commands ###
